disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - weak_delegate
  - trailing_whitespace
  - comment_spacing

opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - PrimaMateria/Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - PrimaMateria/Carthage
  - PrimaMateria/Resources

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
cyclomatic_complexity: 40
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 500
# they can set both implicitly with an array
type_body_length:
  - 500 # warning
  - 600 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: iPhone # excluded via string
identifier_name:
  max_length: # warning and error
    warning: 60
    error: 70
  min_length: # only min_length
    error: 3 # only error
  validates_start_with_lowercase: false
  allowed_symbols:
    - _
  excluded: # excluded via string array
    - id
    - URL
    - p
    - r
    - g
    - b
    - s
    - x
    - y
    - o
    - vm
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
