# Uncomment this line to define a global platform for your project
platform :ios, '11.3'

target 'PrimaMateria' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'CorePlot', '~> 2.2'
    pod 'RxSwift',    '~> 4.0'
    #pod 'RxCocoa',    '~> 4.0'
end

target 'PrimaMateria Debug' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'CorePlot', '~> 2.2'
    pod 'RxSwift',    '~> 4.0'
    #pod 'RxCocoa',    '~> 4.0'
end
