tidy -utf8 -indent actinide.html -m actinide.html
tidy -utf8 -indent alkaliEarthMetal.html -m alkaliEarthMetal.html
tidy -utf8 -indent alkaliMetal.html -m alkaliMetal.html
tidy -utf8 -indent angstrom.html -m angstrom.html
tidy -utf8 -indent atom.html -m atom.html
tidy -utf8 -indent atomicMass.html -m atomicMass.html
tidy -utf8 -indent atomicNumber.html -m atomicNumber.html
tidy -utf8 -indent atomicRadius.html -m atomicRadius.html
tidy -utf8 -indent atomicVolume.html -m atomicVolume.html
tidy -utf8 -indent barn.html -m barn.html
tidy -utf8 -indent boilingPoint.html -m boilingPoint.html
tidy -utf8 -indent cas.html -m cas.html
tidy -utf8 -indent casRegistryNumber.html -m casRegistryNumber.html
tidy -utf8 -indent coefficientOfLinealThermalExpansion.html -m coefficientOfLinealThermalExpansion.html
tidy -utf8 -indent conduction.html -m conduction.html
tidy -utf8 -indent conductivityElectrical.html -m conductivityElectrical.html
tidy -utf8 -indent conductivityThermal.html -m conductivityThermal.html
tidy -utf8 -indent covalentRadius.html -m covalentRadius.html
tidy -utf8 -indent criticalTemperature.html -m criticalTemperature.html
tidy -utf8 -indent crossSection.html -m crossSection.html
tidy -utf8 -indent crystalStructure.html -m crystalStructure.html
tidy -utf8 -indent density.html -m density.html
tidy -utf8 -indent descr.html -m descr.html
tidy -utf8 -indent elasticModulus.html -m elasticModulus.html
tidy -utf8 -indent elasticModulusBulk.html -m elasticModulusBulk.html
tidy -utf8 -indent elasticModulusRigidity.html -m elasticModulusRigidity.html
tidy -utf8 -indent elasticModulusYoungs.html -m elasticModulusYoungs.html
tidy -utf8 -indent electroChemicalEquivalent.html -m electroChemicalEquivalent.html
tidy -utf8 -indent electroConductivity.html -m electroConductivity.html
tidy -utf8 -indent electroNegativity.html -m electroNegativity.html
tidy -utf8 -indent electron.html -m electron.html
tidy -utf8 -indent electronConfiguration.html -m electronConfiguration.html
tidy -utf8 -indent electronWorkFunction.html -m electronWorkFunction.html
tidy -utf8 -indent element.html -m element.html
tidy -utf8 -indent energyLevel.html -m energyLevel.html
tidy -utf8 -indent enthalpies.html -m enthalpies.html
tidy -utf8 -indent enthalpyOfAtomization.html -m enthalpyOfAtomization.html
tidy -utf8 -indent enthalpyOfFusion.html -m enthalpyOfFusion.html
tidy -utf8 -indent enthalpyOfVaporization.html -m enthalpyOfVaporization.html
tidy -utf8 -indent fillingOrbital.html -m fillingOrbital.html
tidy -utf8 -indent flammabilityClass.html -m flammabilityClass.html
tidy -utf8 -indent group.html -m group.html
tidy -utf8 -indent halogen.html -m halogen.html
tidy -utf8 -indent hardnessScaleBrinell.html -m hardnessScaleBrinell.html
tidy -utf8 -indent hardnessScaleMohs.html -m hardnessScaleMohs.html
tidy -utf8 -indent hardnessScaleVickers.html -m hardnessScaleVickers.html
tidy -utf8 -indent hardnessScales.html -m hardnessScales.html
tidy -utf8 -indent heatOfFusion.html -m heatOfFusion.html
tidy -utf8 -indent heatOfVaporization.html -m heatOfVaporization.html
tidy -utf8 -indent incompatibilities.html -m incompatibilities.html
tidy -utf8 -indent index.html -m index.html
tidy -utf8 -indent ionicRadius.html -m ionicRadius.html
tidy -utf8 -indent ionizationPotentials.html -m ionizationPotentials.html
tidy -utf8 -indent iopac.html -m iopac.html
tidy -utf8 -indent lanthanide.html -m lanthanide.html
tidy -utf8 -indent lineSpectra.html -m lineSpectra.html
tidy -utf8 -indent magneticSusceptibility.html -m magneticSusceptibility.html
tidy -utf8 -indent meltingPoint.html -m meltingPoint.html
tidy -utf8 -indent metal.html -m metal.html
tidy -utf8 -indent metalloid.html -m metalloid.html
tidy -utf8 -indent molarHeatCapacity.html -m molarHeatCapacity.html
tidy -utf8 -indent molarVolume.html -m molarVolume.html
tidy -utf8 -indent nanometer.html -m nanometer.html
tidy -utf8 -indent neutron.html -m neutron.html
tidy -utf8 -indent nobleGas.html -m nobleGas.html
tidy -utf8 -indent nonMetal.html -m nonMetal.html
tidy -utf8 -indent nucleus.html -m nucleus.html
tidy -utf8 -indent nuclide.html -m nuclide.html
tidy -utf8 -indent opticalReflectivity.html -m opticalReflectivity.html
tidy -utf8 -indent opticalRefractiveIndex.html -m opticalRefractiveIndex.html
tidy -utf8 -indent orbital.html -m orbital.html
tidy -utf8 -indent orbitalTheory.html -m orbitalTheory.html
tidy -utf8 -indent oxidationStates.html -m oxidationStates.html
tidy -utf8 -indent period.html -m period.html
tidy -utf8 -indent periodicTable.html -m periodicTable.html
tidy -utf8 -indent photon.html -m photon.html
tidy -utf8 -indent proton.html -m proton.html
tidy -utf8 -indent qualitativeSolubility.html -m qualitativeSolubility.html
tidy -utf8 -indent quantum.html -m quantum.html
tidy -utf8 -indent quantumNumber.html -m quantumNumber.html
tidy -utf8 -indent radiation.html -m radiation.html
tidy -utf8 -indent relativeGasDensity.html -m relativeGasDensity.html
tidy -utf8 -indent series.html -m series.html
tidy -utf8 -indent shellModel.html -m shellModel.html
tidy -utf8 -indent specificHeat.html -m specificHeat.html
tidy -utf8 -indent standardCondition.html -m standardCondition.html
tidy -utf8 -indent transactinide.html -m transactinide.html
tidy -utf8 -indent transitionMetal.html -m transitionMetal.html
tidy -utf8 -indent valence.html -m valence.html
tidy -utf8 -indent valenceElectronPotential.html -m valenceElectronPotential.html
tidy -utf8 -indent valenceElectrons.html -m valenceElectrons.html
tidy -utf8 -indent vaporPressure.html -m vaporPressure.html
