tidy -i -asxml ./en.lproj/LoadFailure.html -m ./en.lproj/LoadFailure.html
tidy -i -asxml ./PrimaMateriaHelp/ru/index.html -m ./PrimaMateriaHelp/ru/index.html
tidy -i -asxml ./PrimaMateriaHelp/ru/License.html -m ./PrimaMateriaHelp/ru/License.html
tidy -i -asxml ./PrimaMateriaHelp/ru/GeneralInfo.html -m ./PrimaMateriaHelp/ru/GeneralInfo.html
tidy -i -asxml ./PrimaMateriaHelp/ru/ReleaseNotes.html -m ./PrimaMateriaHelp/ru/ReleaseNotes.html
tidy -i -asxml ./PrimaMateriaHelp/ru/References.html -m ./PrimaMateriaHelp/ru/References.html
tidy -i -asxml ./PrimaMateriaHelp/fr/index.html -m ./PrimaMateriaHelp/fr/index.html
tidy -i -asxml ./PrimaMateriaHelp/fr/License.html -m ./PrimaMateriaHelp/fr/License.html
tidy -i -asxml ./PrimaMateriaHelp/fr/GeneralInfo.html -m ./PrimaMateriaHelp/fr/GeneralInfo.html
tidy -i -asxml ./PrimaMateriaHelp/fr/ReleaseNotes.html -m ./PrimaMateriaHelp/fr/ReleaseNotes.html
tidy -i -asxml ./PrimaMateriaHelp/fr/References.html -m ./PrimaMateriaHelp/fr/References.html
tidy -i -asxml ./PrimaMateriaHelp/es/index.html -m ./PrimaMateriaHelp/es/index.html
tidy -i -asxml ./PrimaMateriaHelp/es/License.html -m ./PrimaMateriaHelp/es/License.html
tidy -i -asxml ./PrimaMateriaHelp/es/GeneralInfo.html -m ./PrimaMateriaHelp/es/GeneralInfo.html
tidy -i -asxml ./PrimaMateriaHelp/es/ReleaseNotes.html -m ./PrimaMateriaHelp/es/ReleaseNotes.html
tidy -i -asxml ./PrimaMateriaHelp/es/References.html -m ./PrimaMateriaHelp/es/References.html
tidy -i -asxml ./PrimaMateriaHelp/en/index.html -m ./PrimaMateriaHelp/en/index.html
tidy -i -asxml ./PrimaMateriaHelp/en/License.html -m ./PrimaMateriaHelp/en/License.html
tidy -i -asxml ./PrimaMateriaHelp/en/GeneralInfo.html -m ./PrimaMateriaHelp/en/GeneralInfo.html
tidy -i -asxml ./PrimaMateriaHelp/en/ReleaseNotes.html -m ./PrimaMateriaHelp/en/ReleaseNotes.html
tidy -i -asxml ./PrimaMateriaHelp/en/References.html -m ./PrimaMateriaHelp/en/References.html
tidy -i -asxml ./es.lproj/LoadFailure.html -m ./es.lproj/LoadFailure.html
tidy -i -asxml ./Base.lproj/LoadFailure.html -m ./Base.lproj/LoadFailure.html
tidy -i -asxml ./ElementTipHelp/ionizationPotentials.html -m ./ElementTipHelp/ionizationPotentials.html
tidy -i -asxml ./ElementTipHelp/atom.html -m ./ElementTipHelp/atom.html
tidy -i -asxml ./ElementTipHelp/photon.html -m ./ElementTipHelp/photon.html
tidy -i -asxml ./ElementTipHelp/nonMetal.html -m ./ElementTipHelp/nonMetal.html
tidy -i -asxml ./ElementTipHelp/oxidationStates.html -m ./ElementTipHelp/oxidationStates.html
tidy -i -asxml ./ElementTipHelp/magneticSusceptibility.html -m ./ElementTipHelp/magneticSusceptibility.html
tidy -i -asxml ./ElementTipHelp/alkaliEarthMetal.html -m ./ElementTipHelp/alkaliEarthMetal.html
tidy -i -asxml ./ElementTipHelp/barn.html -m ./ElementTipHelp/barn.html
tidy -i -asxml ./ElementTipHelp/enthalpyOfVaporization.html -m ./ElementTipHelp/enthalpyOfVaporization.html
tidy -i -asxml ./ElementTipHelp/element.html -m ./ElementTipHelp/element.html
tidy -i -asxml ./ElementTipHelp/electroChemicalEquivalent.html -m ./ElementTipHelp/electroChemicalEquivalent.html
tidy -i -asxml ./ElementTipHelp/valenceElectronPotential.html -m ./ElementTipHelp/valenceElectronPotential.html
tidy -i -asxml ./ElementTipHelp/alkaliMetal.html -m ./ElementTipHelp/alkaliMetal.html
tidy -i -asxml ./ElementTipHelp/covalentRadius.html -m ./ElementTipHelp/covalentRadius.html
tidy -i -asxml ./ElementTipHelp/density.html -m ./ElementTipHelp/density.html
tidy -i -asxml ./ElementTipHelp/metalloid.html -m ./ElementTipHelp/metalloid.html
tidy -i -asxml ./ElementTipHelp/index.html -m ./ElementTipHelp/index.html
tidy -i -asxml ./ElementTipHelp/fillingOrbital.html -m ./ElementTipHelp/fillingOrbital.html
tidy -i -asxml ./ElementTipHelp/hardnessScales.html -m ./ElementTipHelp/hardnessScales.html
tidy -i -asxml ./ElementTipHelp/energyLevel.html -m ./ElementTipHelp/energyLevel.html
tidy -i -asxml ./ElementTipHelp/radiation.html -m ./ElementTipHelp/radiation.html
tidy -i -asxml ./ElementTipHelp/relativeGasDensity.html -m ./ElementTipHelp/relativeGasDensity.html
tidy -i -asxml ./ElementTipHelp/conduction.html -m ./ElementTipHelp/conduction.html
tidy -i -asxml ./ElementTipHelp/group.html -m ./ElementTipHelp/group.html
tidy -i -asxml ./ElementTipHelp/angstrom.html -m ./ElementTipHelp/angstrom.html
tidy -i -asxml ./ElementTipHelp/quantumNumber.html -m ./ElementTipHelp/quantumNumber.html
tidy -i -asxml ./ElementTipHelp/transitionMetal.html -m ./ElementTipHelp/transitionMetal.html
tidy -i -asxml ./ElementTipHelp/coefficientOfLinealThermalExpansion.html -m ./ElementTipHelp/coefficientOfLinealThermalExpansion.h
tidy -i -asxml ./ElementTipHelp/series.html -m ./ElementTipHelp/series.html
tidy -i -asxml ./ElementTipHelp/atomicVolume.html -m ./ElementTipHelp/atomicVolume.html
tidy -i -asxml ./ElementTipHelp/casRegistryNumber.html -m ./ElementTipHelp/casRegistryNumber.html
tidy -i -asxml ./ElementTipHelp/conductivityElectrical.html -m ./ElementTipHelp/conductivityElectrical.html
tidy -i -asxml ./ElementTipHelp/quantum.html -m ./ElementTipHelp/quantum.html
tidy -i -asxml ./ElementTipHelp/transactinide.html -m ./ElementTipHelp/transactinide.html
tidy -i -asxml ./ElementTipHelp/elasticModulusBulk.html -m ./ElementTipHelp/elasticModulusBulk.html
tidy -i -asxml ./ElementTipHelp/electronWorkFunction.html -m ./ElementTipHelp/electronWorkFunction.html
tidy -i -asxml ./ElementTipHelp/elasticModulus.html -m ./ElementTipHelp/elasticModulus.html
tidy -i -asxml ./ElementTipHelp/periodicTable.html -m ./ElementTipHelp/periodicTable.html
tidy -i -asxml ./ElementTipHelp/enthalpies.html -m ./ElementTipHelp/enthalpies.html
tidy -i -asxml ./ElementTipHelp/atomicNumber.html -m ./ElementTipHelp/atomicNumber.html
tidy -i -asxml ./ElementTipHelp/standardCondition.html -m ./ElementTipHelp/standardCondition.html
tidy -i -asxml ./ElementTipHelp/neutron.html -m ./ElementTipHelp/neutron.html
tidy -i -asxml ./ElementTipHelp/valence.html -m ./ElementTipHelp/valence.html
tidy -i -asxml ./ElementTipHelp/elasticModulusRigidity.html -m ./ElementTipHelp/elasticModulusRigidity.html
tidy -i -asxml ./ElementTipHelp/specificHeat.html -m ./ElementTipHelp/specificHeat.html
tidy -i -asxml ./ElementTipHelp/orbitalTheory.html -m ./ElementTipHelp/orbitalTheory.html
tidy -i -asxml ./ElementTipHelp/molarVolume.html -m ./ElementTipHelp/molarVolume.html
tidy -i -asxml ./ElementTipHelp/meltingPoint.html -m ./ElementTipHelp/meltingPoint.html
tidy -i -asxml ./ElementTipHelp/electron.html -m ./ElementTipHelp/electron.html
tidy -i -asxml ./ElementTipHelp/heatOfVaporization.html -m ./ElementTipHelp/heatOfVaporization.html
tidy -i -asxml ./ElementTipHelp/hardnessScaleMohs.html -m ./ElementTipHelp/hardnessScaleMohs.html
tidy -i -asxml ./ElementTipHelp/halogen.html -m ./ElementTipHelp/halogen.html
tidy -i -asxml ./ElementTipHelp/opticalReflectivity.html -m ./ElementTipHelp/opticalReflectivity.html
tidy -i -asxml ./ElementTipHelp/crystalStructure.html -m ./ElementTipHelp/crystalStructure.html
tidy -i -asxml ./ElementTipHelp/enthalpyOfAtomization.html -m ./ElementTipHelp/enthalpyOfAtomization.html
tidy -i -asxml ./ElementTipHelp/orbital.html -m ./ElementTipHelp/orbital.html
tidy -i -asxml ./ElementTipHelp/qualitativeSolubility.html -m ./ElementTipHelp/qualitativeSolubility.html
tidy -i -asxml ./ElementTipHelp/valenceElectrons.html -m ./ElementTipHelp/valenceElectrons.html
tidy -i -asxml ./ElementTipHelp/nanometer.html -m ./ElementTipHelp/nanometer.html
tidy -i -asxml ./ElementTipHelp/nuclide.html -m ./ElementTipHelp/nuclide.html
tidy -i -asxml ./ElementTipHelp/heatOfFusion.html -m ./ElementTipHelp/heatOfFusion.html
tidy -i -asxml ./ElementTipHelp/molarHeatCapacity.html -m ./ElementTipHelp/molarHeatCapacity.html
tidy -i -asxml ./ElementTipHelp/enthalpyOfFusion.html -m ./ElementTipHelp/enthalpyOfFusion.html
tidy -i -asxml ./ElementTipHelp/flammabilityClass.html -m ./ElementTipHelp/flammabilityClass.html
tidy -i -asxml ./ElementTipHelp/ionicRadius.html -m ./ElementTipHelp/ionicRadius.html
tidy -i -asxml ./ElementTipHelp/electroNegativity.html -m ./ElementTipHelp/electroNegativity.html
tidy -i -asxml ./ElementTipHelp/elasticModulusYoungs.html -m ./ElementTipHelp/elasticModulusYoungs.html
tidy -i -asxml ./ElementTipHelp/shellModel.html -m ./ElementTipHelp/shellModel.html
tidy -i -asxml ./ElementTipHelp/crossSection.html -m ./ElementTipHelp/crossSection.html
tidy -i -asxml ./ElementTipHelp/conductivityThermal.html -m ./ElementTipHelp/conductivityThermal.html
tidy -i -asxml ./ElementTipHelp/atomicRadius.html -m ./ElementTipHelp/atomicRadius.html
tidy -i -asxml ./ElementTipHelp/electroConductivity.html -m ./ElementTipHelp/electroConductivity.html
tidy -i -asxml ./ElementTipHelp/hardnessScaleBrinell.html -m ./ElementTipHelp/hardnessScaleBrinell.html
tidy -i -asxml ./ElementTipHelp/opticalRefractiveIndex.html -m ./ElementTipHelp/opticalRefractiveIndex.html
tidy -i -asxml ./ElementTipHelp/criticalTemperature.html -m ./ElementTipHelp/criticalTemperature.html
tidy -i -asxml ./ElementTipHelp/nucleus.html -m ./ElementTipHelp/nucleus.html
tidy -i -asxml ./ElementTipHelp/incompatibilities.html -m ./ElementTipHelp/incompatibilities.html
tidy -i -asxml ./ElementTipHelp/atomicMass.html -m ./ElementTipHelp/atomicMass.html
tidy -i -asxml ./ElementTipHelp/vaporPressure.html -m ./ElementTipHelp/vaporPressure.html
tidy -i -asxml ./ElementTipHelp/hardnessScaleVickers.html -m ./ElementTipHelp/hardnessScaleVickers.html
tidy -i -asxml ./ElementTipHelp/electronConfiguration.html -m ./ElementTipHelp/electronConfiguration.html
tidy -i -asxml ./ElementTipHelp/cas.html -m ./ElementTipHelp/cas.html
tidy -i -asxml ./ElementTipHelp/nobleGas.html -m ./ElementTipHelp/nobleGas.html
tidy -i -asxml ./ElementTipHelp/descr.html -m ./ElementTipHelp/descr.html
tidy -i -asxml ./ElementTipHelp/period.html -m ./ElementTipHelp/period.html
tidy -i -asxml ./ElementTipHelp/metal.html -m ./ElementTipHelp/metal.html
tidy -i -asxml ./ElementTipHelp/boilingPoint.html -m ./ElementTipHelp/boilingPoint.html
tidy -i -asxml ./ElementTipHelp/lanthanide.html -m ./ElementTipHelp/lanthanide.html
tidy -i -asxml ./ElementTipHelp/proton.html -m ./ElementTipHelp/proton.html
tidy -i -asxml ./ElementTipHelp/lineSpectra.html -m ./ElementTipHelp/lineSpectra.html
tidy -i -asxml ./ElementTipHelp/iopac.html -m ./ElementTipHelp/iopac.html
tidy -i -asxml ./ElementTipHelp/actinide.html -m ./ElementTipHelp/actinide.html
tidy -i -asxml ./ru.lproj/LoadFailure.html -m ./ru.lproj/LoadFailure.html
tidy -i -asxml ./fr.lproj/LoadFailure.html -m ./fr.lproj/LoadFailure.html
