tidy -i -asxml ./en.lproj/LoadFailure.html -m ./en.lproj/LoadFailure.html
tidy -i -asxml ./PrimaMateriaHelp/ru/index.html -m ./PrimaMateriaHelp/ru/index.html
tidy -i -asxml ./PrimaMateriaHelp/ru/License.html -m ./PrimaMateriaHelp/ru/License.html
tidy -i -asxml ./PrimaMateriaHelp/ru/GeneralInfo.html -m ./PrimaMateriaHelp/ru/GeneralInfo.html
tidy -i -asxml ./PrimaMateriaHelp/ru/ReleaseNotes.html -m ./PrimaMateriaHelp/ru/ReleaseNotes.html
tidy -i -asxml ./PrimaMateriaHelp/ru/References.html -m ./PrimaMateriaHelp/ru/References.html
tidy -i -asxml ./PrimaMateriaHelp/fr/index.html -m ./PrimaMateriaHelp/fr/index.html
tidy -i -asxml ./PrimaMateriaHelp/fr/License.html -m ./PrimaMateriaHelp/fr/License.html
tidy -i -asxml ./PrimaMateriaHelp/fr/GeneralInfo.html -m ./PrimaMateriaHelp/fr/GeneralInfo.html
tidy -i -asxml ./PrimaMateriaHelp/fr/ReleaseNotes.html -m ./PrimaMateriaHelp/fr/ReleaseNotes.html
tidy -i -asxml ./PrimaMateriaHelp/fr/References.html -m ./PrimaMateriaHelp/fr/References.html
tidy -i -asxml ./PrimaMateriaHelp/es/index.html -m ./PrimaMateriaHelp/es/index.html
tidy -i -asxml ./PrimaMateriaHelp/es/License.html -m ./PrimaMateriaHelp/es/License.html
tidy -i -asxml ./PrimaMateriaHelp/es/GeneralInfo.html -m ./PrimaMateriaHelp/es/GeneralInfo.html
tidy -i -asxml ./PrimaMateriaHelp/es/ReleaseNotes.html -m ./PrimaMateriaHelp/es/ReleaseNotes.html
tidy -i -asxml ./PrimaMateriaHelp/es/References.html -m ./PrimaMateriaHelp/es/References.html
tidy -i -asxml ./PrimaMateriaHelp/en/index.html -m ./PrimaMateriaHelp/en/index.html
tidy -i -asxml ./PrimaMateriaHelp/en/License.html -m ./PrimaMateriaHelp/en/License.html
tidy -i -asxml ./PrimaMateriaHelp/en/GeneralInfo.html -m ./PrimaMateriaHelp/en/GeneralInfo.html
tidy -i -asxml ./PrimaMateriaHelp/en/ReleaseNotes.html -m ./PrimaMateriaHelp/en/ReleaseNotes.html
tidy -i -asxml ./PrimaMateriaHelp/en/References.html -m ./PrimaMateriaHelp/en/References.html
tidy -i -asxml ./es.lproj/LoadFailure.html -m ./es.lproj/LoadFailure.html
tidy -i -asxml ./Base.lproj/LoadFailure.html -m ./Base.lproj/LoadFailure.html
tidy -i -asxml ./ElementTipHelp/ru/ionizationPotentials.html -m ./ElementTipHelp/ru/ionizationPotentials.html
tidy -i -asxml ./ElementTipHelp/ru/atom.html -m ./ElementTipHelp/ru/atom.html
tidy -i -asxml ./ElementTipHelp/ru/photon.html -m ./ElementTipHelp/ru/photon.html
tidy -i -asxml ./ElementTipHelp/ru/nonMetal.html -m ./ElementTipHelp/ru/nonMetal.html
tidy -i -asxml ./ElementTipHelp/ru/oxidationStates.html -m ./ElementTipHelp/ru/oxidationStates.html
tidy -i -asxml ./ElementTipHelp/ru/magneticSusceptibility.html -m ./ElementTipHelp/ru/magneticSusceptibility.html
tidy -i -asxml ./ElementTipHelp/ru/alkaliEarthMetal.html -m ./ElementTipHelp/ru/alkaliEarthMetal.html
tidy -i -asxml ./ElementTipHelp/ru/barn.html -m ./ElementTipHelp/ru/barn.html
tidy -i -asxml ./ElementTipHelp/ru/enthalpyOfVaporization.html -m ./ElementTipHelp/ru/enthalpyOfVaporization.html
tidy -i -asxml ./ElementTipHelp/ru/element.html -m ./ElementTipHelp/ru/element.html
tidy -i -asxml ./ElementTipHelp/ru/electroChemicalEquivalent.html -m ./ElementTipHelp/ru/electroChemicalEquivalent.html
tidy -i -asxml ./ElementTipHelp/ru/valenceElectronPotential.html -m ./ElementTipHelp/ru/valenceElectronPotential.html
tidy -i -asxml ./ElementTipHelp/ru/alkaliMetal.html -m ./ElementTipHelp/ru/alkaliMetal.html
tidy -i -asxml ./ElementTipHelp/ru/covalentRadius.html -m ./ElementTipHelp/ru/covalentRadius.html
tidy -i -asxml ./ElementTipHelp/ru/density.html -m ./ElementTipHelp/ru/density.html
tidy -i -asxml ./ElementTipHelp/ru/metalloid.html -m ./ElementTipHelp/ru/metalloid.html
tidy -i -asxml ./ElementTipHelp/ru/index.html -m ./ElementTipHelp/ru/index.html
tidy -i -asxml ./ElementTipHelp/ru/fillingOrbital.html -m ./ElementTipHelp/ru/fillingOrbital.html
tidy -i -asxml ./ElementTipHelp/ru/hardnessScales.html -m ./ElementTipHelp/ru/hardnessScales.html
tidy -i -asxml ./ElementTipHelp/ru/energyLevel.html -m ./ElementTipHelp/ru/energyLevel.html
tidy -i -asxml ./ElementTipHelp/ru/radiation.html -m ./ElementTipHelp/ru/radiation.html
tidy -i -asxml ./ElementTipHelp/ru/relativeGasDensity.html -m ./ElementTipHelp/ru/relativeGasDensity.html
tidy -i -asxml ./ElementTipHelp/ru/conduction.html -m ./ElementTipHelp/ru/conduction.html
tidy -i -asxml ./ElementTipHelp/ru/group.html -m ./ElementTipHelp/ru/group.html
tidy -i -asxml ./ElementTipHelp/ru/angstrom.html -m ./ElementTipHelp/ru/angstrom.html
tidy -i -asxml ./ElementTipHelp/ru/quantumNumber.html -m ./ElementTipHelp/ru/quantumNumber.html
tidy -i -asxml ./ElementTipHelp/ru/transitionMetal.html -m ./ElementTipHelp/ru/transitionMetal.html
tidy -i -asxml ./ElementTipHelp/ru/coefficientOfLinealThermalExpansion.html -m ./ElementTipHelp/ru/coefficientOfLinealThermalExpansion.html
tidy -i -asxml ./ElementTipHelp/ru/series.html -m ./ElementTipHelp/ru/series.html
tidy -i -asxml ./ElementTipHelp/ru/atomicVolume.html -m ./ElementTipHelp/ru/atomicVolume.html
tidy -i -asxml ./ElementTipHelp/ru/casRegistryNumber.html -m ./ElementTipHelp/ru/casRegistryNumber.html
tidy -i -asxml ./ElementTipHelp/ru/conductivityElectrical.html -m ./ElementTipHelp/ru/conductivityElectrical.html
tidy -i -asxml ./ElementTipHelp/ru/quantum.html -m ./ElementTipHelp/ru/quantum.html
tidy -i -asxml ./ElementTipHelp/ru/transactinide.html -m ./ElementTipHelp/ru/transactinide.html
tidy -i -asxml ./ElementTipHelp/ru/elasticModulusBulk.html -m ./ElementTipHelp/ru/elasticModulusBulk.html
tidy -i -asxml ./ElementTipHelp/ru/electronWorkFunction.html -m ./ElementTipHelp/ru/electronWorkFunction.html
tidy -i -asxml ./ElementTipHelp/ru/elasticModulus.html -m ./ElementTipHelp/ru/elasticModulus.html
tidy -i -asxml ./ElementTipHelp/ru/periodicTable.html -m ./ElementTipHelp/ru/periodicTable.html
tidy -i -asxml ./ElementTipHelp/ru/enthalpies.html -m ./ElementTipHelp/ru/enthalpies.html
tidy -i -asxml ./ElementTipHelp/ru/atomicNumber.html -m ./ElementTipHelp/ru/atomicNumber.html
tidy -i -asxml ./ElementTipHelp/ru/standardCondition.html -m ./ElementTipHelp/ru/standardCondition.html
tidy -i -asxml ./ElementTipHelp/ru/neutron.html -m ./ElementTipHelp/ru/neutron.html
tidy -i -asxml ./ElementTipHelp/ru/valence.html -m ./ElementTipHelp/ru/valence.html
tidy -i -asxml ./ElementTipHelp/ru/elasticModulusRigidity.html -m ./ElementTipHelp/ru/elasticModulusRigidity.html
tidy -i -asxml ./ElementTipHelp/ru/specificHeat.html -m ./ElementTipHelp/ru/specificHeat.html
tidy -i -asxml ./ElementTipHelp/ru/orbitalTheory.html -m ./ElementTipHelp/ru/orbitalTheory.html
tidy -i -asxml ./ElementTipHelp/ru/molarVolume.html -m ./ElementTipHelp/ru/molarVolume.html
tidy -i -asxml ./ElementTipHelp/ru/meltingPoint.html -m ./ElementTipHelp/ru/meltingPoint.html
tidy -i -asxml ./ElementTipHelp/ru/electron.html -m ./ElementTipHelp/ru/electron.html
tidy -i -asxml ./ElementTipHelp/ru/heatOfVaporization.html -m ./ElementTipHelp/ru/heatOfVaporization.html
tidy -i -asxml ./ElementTipHelp/ru/hardnessScaleMohs.html -m ./ElementTipHelp/ru/hardnessScaleMohs.html
tidy -i -asxml ./ElementTipHelp/ru/halogen.html -m ./ElementTipHelp/ru/halogen.html
tidy -i -asxml ./ElementTipHelp/ru/opticalReflectivity.html -m ./ElementTipHelp/ru/opticalReflectivity.html
tidy -i -asxml ./ElementTipHelp/ru/crystalStructure.html -m ./ElementTipHelp/ru/crystalStructure.html
tidy -i -asxml ./ElementTipHelp/ru/enthalpyOfAtomization.html -m ./ElementTipHelp/ru/enthalpyOfAtomization.html
tidy -i -asxml ./ElementTipHelp/ru/orbital.html -m ./ElementTipHelp/ru/orbital.html
tidy -i -asxml ./ElementTipHelp/ru/qualitativeSolubility.html -m ./ElementTipHelp/ru/qualitativeSolubility.html
tidy -i -asxml ./ElementTipHelp/ru/valenceElectrons.html -m ./ElementTipHelp/ru/valenceElectrons.html
tidy -i -asxml ./ElementTipHelp/ru/nanometer.html -m ./ElementTipHelp/ru/nanometer.html
tidy -i -asxml ./ElementTipHelp/ru/nuclide.html -m ./ElementTipHelp/ru/nuclide.html
tidy -i -asxml ./ElementTipHelp/ru/heatOfFusion.html -m ./ElementTipHelp/ru/heatOfFusion.html
tidy -i -asxml ./ElementTipHelp/ru/molarHeatCapacity.html -m ./ElementTipHelp/ru/molarHeatCapacity.html
tidy -i -asxml ./ElementTipHelp/ru/enthalpyOfFusion.html -m ./ElementTipHelp/ru/enthalpyOfFusion.html
tidy -i -asxml ./ElementTipHelp/ru/flammabilityClass.html -m ./ElementTipHelp/ru/flammabilityClass.html
tidy -i -asxml ./ElementTipHelp/ru/ionicRadius.html -m ./ElementTipHelp/ru/ionicRadius.html
tidy -i -asxml ./ElementTipHelp/ru/electroNegativity.html -m ./ElementTipHelp/ru/electroNegativity.html
tidy -i -asxml ./ElementTipHelp/ru/elasticModulusYoungs.html -m ./ElementTipHelp/ru/elasticModulusYoungs.html
tidy -i -asxml ./ElementTipHelp/ru/shellModel.html -m ./ElementTipHelp/ru/shellModel.html
tidy -i -asxml ./ElementTipHelp/ru/crossSection.html -m ./ElementTipHelp/ru/crossSection.html
tidy -i -asxml ./ElementTipHelp/ru/conductivityThermal.html -m ./ElementTipHelp/ru/conductivityThermal.html
tidy -i -asxml ./ElementTipHelp/ru/atomicRadius.html -m ./ElementTipHelp/ru/atomicRadius.html
tidy -i -asxml ./ElementTipHelp/ru/electroConductivity.html -m ./ElementTipHelp/ru/electroConductivity.html
tidy -i -asxml ./ElementTipHelp/ru/hardnessScaleBrinell.html -m ./ElementTipHelp/ru/hardnessScaleBrinell.html
tidy -i -asxml ./ElementTipHelp/ru/opticalRefractiveIndex.html -m ./ElementTipHelp/ru/opticalRefractiveIndex.html
tidy -i -asxml ./ElementTipHelp/ru/criticalTemperature.html -m ./ElementTipHelp/ru/criticalTemperature.html
tidy -i -asxml ./ElementTipHelp/ru/nucleus.html -m ./ElementTipHelp/ru/nucleus.html
tidy -i -asxml ./ElementTipHelp/ru/incompatibilities.html -m ./ElementTipHelp/ru/incompatibilities.html
tidy -i -asxml ./ElementTipHelp/ru/atomicMass.html -m ./ElementTipHelp/ru/atomicMass.html
tidy -i -asxml ./ElementTipHelp/ru/vaporPressure.html -m ./ElementTipHelp/ru/vaporPressure.html
tidy -i -asxml ./ElementTipHelp/ru/hardnessScaleVickers.html -m ./ElementTipHelp/ru/hardnessScaleVickers.html
tidy -i -asxml ./ElementTipHelp/ru/electronConfiguration.html -m ./ElementTipHelp/ru/electronConfiguration.html
tidy -i -asxml ./ElementTipHelp/ru/cas.html -m ./ElementTipHelp/ru/cas.html
tidy -i -asxml ./ElementTipHelp/ru/nobleGas.html -m ./ElementTipHelp/ru/nobleGas.html
tidy -i -asxml ./ElementTipHelp/ru/descr.html -m ./ElementTipHelp/ru/descr.html
tidy -i -asxml ./ElementTipHelp/ru/period.html -m ./ElementTipHelp/ru/period.html
tidy -i -asxml ./ElementTipHelp/ru/metal.html -m ./ElementTipHelp/ru/metal.html
tidy -i -asxml ./ElementTipHelp/ru/boilingPoint.html -m ./ElementTipHelp/ru/boilingPoint.html
tidy -i -asxml ./ElementTipHelp/ru/lanthanide.html -m ./ElementTipHelp/ru/lanthanide.html
tidy -i -asxml ./ElementTipHelp/ru/proton.html -m ./ElementTipHelp/ru/proton.html
tidy -i -asxml ./ElementTipHelp/ru/lineSpectra.html -m ./ElementTipHelp/ru/lineSpectra.html
tidy -i -asxml ./ElementTipHelp/ru/iopac.html -m ./ElementTipHelp/ru/iopac.html
tidy -i -asxml ./ElementTipHelp/ru/actinide.html -m ./ElementTipHelp/ru/actinide.html
tidy -i -asxml ./ElementTipHelp/fr/ionizationPotentials.html -m ./ElementTipHelp/fr/ionizationPotentials.html
tidy -i -asxml ./ElementTipHelp/fr/atom.html -m ./ElementTipHelp/fr/atom.html
tidy -i -asxml ./ElementTipHelp/fr/photon.html -m ./ElementTipHelp/fr/photon.html
tidy -i -asxml ./ElementTipHelp/fr/nonMetal.html -m ./ElementTipHelp/fr/nonMetal.html
tidy -i -asxml ./ElementTipHelp/fr/oxidationStates.html -m ./ElementTipHelp/fr/oxidationStates.html
tidy -i -asxml ./ElementTipHelp/fr/magneticSusceptibility.html -m ./ElementTipHelp/fr/magneticSusceptibility.html
tidy -i -asxml ./ElementTipHelp/fr/alkaliEarthMetal.html -m ./ElementTipHelp/fr/alkaliEarthMetal.html
tidy -i -asxml ./ElementTipHelp/fr/barn.html -m ./ElementTipHelp/fr/barn.html
tidy -i -asxml ./ElementTipHelp/fr/enthalpyOfVaporization.html -m ./ElementTipHelp/fr/enthalpyOfVaporization.html
tidy -i -asxml ./ElementTipHelp/fr/element.html -m ./ElementTipHelp/fr/element.html
tidy -i -asxml ./ElementTipHelp/fr/electroChemicalEquivalent.html -m ./ElementTipHelp/fr/electroChemicalEquivalent.html
tidy -i -asxml ./ElementTipHelp/fr/valenceElectronPotential.html -m ./ElementTipHelp/fr/valenceElectronPotential.html
tidy -i -asxml ./ElementTipHelp/fr/alkaliMetal.html -m ./ElementTipHelp/fr/alkaliMetal.html
tidy -i -asxml ./ElementTipHelp/fr/covalentRadius.html -m ./ElementTipHelp/fr/covalentRadius.html
tidy -i -asxml ./ElementTipHelp/fr/density.html -m ./ElementTipHelp/fr/density.html
tidy -i -asxml ./ElementTipHelp/fr/metalloid.html -m ./ElementTipHelp/fr/metalloid.html
tidy -i -asxml ./ElementTipHelp/fr/index.html -m ./ElementTipHelp/fr/index.html
tidy -i -asxml ./ElementTipHelp/fr/fillingOrbital.html -m ./ElementTipHelp/fr/fillingOrbital.html
tidy -i -asxml ./ElementTipHelp/fr/hardnessScales.html -m ./ElementTipHelp/fr/hardnessScales.html
tidy -i -asxml ./ElementTipHelp/fr/energyLevel.html -m ./ElementTipHelp/fr/energyLevel.html
tidy -i -asxml ./ElementTipHelp/fr/radiation.html -m ./ElementTipHelp/fr/radiation.html
tidy -i -asxml ./ElementTipHelp/fr/relativeGasDensity.html -m ./ElementTipHelp/fr/relativeGasDensity.html
tidy -i -asxml ./ElementTipHelp/fr/conduction.html -m ./ElementTipHelp/fr/conduction.html
tidy -i -asxml ./ElementTipHelp/fr/group.html -m ./ElementTipHelp/fr/group.html
tidy -i -asxml ./ElementTipHelp/fr/angstrom.html -m ./ElementTipHelp/fr/angstrom.html
tidy -i -asxml ./ElementTipHelp/fr/quantumNumber.html -m ./ElementTipHelp/fr/quantumNumber.html
tidy -i -asxml ./ElementTipHelp/fr/transitionMetal.html -m ./ElementTipHelp/fr/transitionMetal.html
tidy -i -asxml ./ElementTipHelp/fr/coefficientOfLinealThermalExpansion.html -m ./ElementTipHelp/fr/coefficientOfLinealThermalExpansion.html
tidy -i -asxml ./ElementTipHelp/fr/series.html -m ./ElementTipHelp/fr/series.html
tidy -i -asxml ./ElementTipHelp/fr/atomicVolume.html -m ./ElementTipHelp/fr/atomicVolume.html
tidy -i -asxml ./ElementTipHelp/fr/casRegistryNumber.html -m ./ElementTipHelp/fr/casRegistryNumber.html
tidy -i -asxml ./ElementTipHelp/fr/conductivityElectrical.html -m ./ElementTipHelp/fr/conductivityElectrical.html
tidy -i -asxml ./ElementTipHelp/fr/quantum.html -m ./ElementTipHelp/fr/quantum.html
tidy -i -asxml ./ElementTipHelp/fr/transactinide.html -m ./ElementTipHelp/fr/transactinide.html
tidy -i -asxml ./ElementTipHelp/fr/elasticModulusBulk.html -m ./ElementTipHelp/fr/elasticModulusBulk.html
tidy -i -asxml ./ElementTipHelp/fr/electronWorkFunction.html -m ./ElementTipHelp/fr/electronWorkFunction.html
tidy -i -asxml ./ElementTipHelp/fr/elasticModulus.html -m ./ElementTipHelp/fr/elasticModulus.html
tidy -i -asxml ./ElementTipHelp/fr/periodicTable.html -m ./ElementTipHelp/fr/periodicTable.html
tidy -i -asxml ./ElementTipHelp/fr/enthalpies.html -m ./ElementTipHelp/fr/enthalpies.html
tidy -i -asxml ./ElementTipHelp/fr/atomicNumber.html -m ./ElementTipHelp/fr/atomicNumber.html
tidy -i -asxml ./ElementTipHelp/fr/standardCondition.html -m ./ElementTipHelp/fr/standardCondition.html
tidy -i -asxml ./ElementTipHelp/fr/neutron.html -m ./ElementTipHelp/fr/neutron.html
tidy -i -asxml ./ElementTipHelp/fr/valence.html -m ./ElementTipHelp/fr/valence.html
tidy -i -asxml ./ElementTipHelp/fr/elasticModulusRigidity.html -m ./ElementTipHelp/fr/elasticModulusRigidity.html
tidy -i -asxml ./ElementTipHelp/fr/specificHeat.html -m ./ElementTipHelp/fr/specificHeat.html
tidy -i -asxml ./ElementTipHelp/fr/orbitalTheory.html -m ./ElementTipHelp/fr/orbitalTheory.html
tidy -i -asxml ./ElementTipHelp/fr/molarVolume.html -m ./ElementTipHelp/fr/molarVolume.html
tidy -i -asxml ./ElementTipHelp/fr/meltingPoint.html -m ./ElementTipHelp/fr/meltingPoint.html
tidy -i -asxml ./ElementTipHelp/fr/electron.html -m ./ElementTipHelp/fr/electron.html
tidy -i -asxml ./ElementTipHelp/fr/heatOfVaporization.html -m ./ElementTipHelp/fr/heatOfVaporization.html
tidy -i -asxml ./ElementTipHelp/fr/hardnessScaleMohs.html -m ./ElementTipHelp/fr/hardnessScaleMohs.html
tidy -i -asxml ./ElementTipHelp/fr/halogen.html -m ./ElementTipHelp/fr/halogen.html
tidy -i -asxml ./ElementTipHelp/fr/opticalReflectivity.html -m ./ElementTipHelp/fr/opticalReflectivity.html
tidy -i -asxml ./ElementTipHelp/fr/crystalStructure.html -m ./ElementTipHelp/fr/crystalStructure.html
tidy -i -asxml ./ElementTipHelp/fr/enthalpyOfAtomization.html -m ./ElementTipHelp/fr/enthalpyOfAtomization.html
tidy -i -asxml ./ElementTipHelp/fr/orbital.html -m ./ElementTipHelp/fr/orbital.html
tidy -i -asxml ./ElementTipHelp/fr/qualitativeSolubility.html -m ./ElementTipHelp/fr/qualitativeSolubility.html
tidy -i -asxml ./ElementTipHelp/fr/valenceElectrons.html -m ./ElementTipHelp/fr/valenceElectrons.html
tidy -i -asxml ./ElementTipHelp/fr/nanometer.html -m ./ElementTipHelp/fr/nanometer.html
tidy -i -asxml ./ElementTipHelp/fr/nuclide.html -m ./ElementTipHelp/fr/nuclide.html
tidy -i -asxml ./ElementTipHelp/fr/heatOfFusion.html -m ./ElementTipHelp/fr/heatOfFusion.html
tidy -i -asxml ./ElementTipHelp/fr/molarHeatCapacity.html -m ./ElementTipHelp/fr/molarHeatCapacity.html
tidy -i -asxml ./ElementTipHelp/fr/enthalpyOfFusion.html -m ./ElementTipHelp/fr/enthalpyOfFusion.html
tidy -i -asxml ./ElementTipHelp/fr/flammabilityClass.html -m ./ElementTipHelp/fr/flammabilityClass.html
tidy -i -asxml ./ElementTipHelp/fr/ionicRadius.html -m ./ElementTipHelp/fr/ionicRadius.html
tidy -i -asxml ./ElementTipHelp/fr/electroNegativity.html -m ./ElementTipHelp/fr/electroNegativity.html
tidy -i -asxml ./ElementTipHelp/fr/elasticModulusYoungs.html -m ./ElementTipHelp/fr/elasticModulusYoungs.html
tidy -i -asxml ./ElementTipHelp/fr/shellModel.html -m ./ElementTipHelp/fr/shellModel.html
tidy -i -asxml ./ElementTipHelp/fr/crossSection.html -m ./ElementTipHelp/fr/crossSection.html
tidy -i -asxml ./ElementTipHelp/fr/conductivityThermal.html -m ./ElementTipHelp/fr/conductivityThermal.html
tidy -i -asxml ./ElementTipHelp/fr/atomicRadius.html -m ./ElementTipHelp/fr/atomicRadius.html
tidy -i -asxml ./ElementTipHelp/fr/electroConductivity.html -m ./ElementTipHelp/fr/electroConductivity.html
tidy -i -asxml ./ElementTipHelp/fr/hardnessScaleBrinell.html -m ./ElementTipHelp/fr/hardnessScaleBrinell.html
tidy -i -asxml ./ElementTipHelp/fr/opticalRefractiveIndex.html -m ./ElementTipHelp/fr/opticalRefractiveIndex.html
tidy -i -asxml ./ElementTipHelp/fr/criticalTemperature.html -m ./ElementTipHelp/fr/criticalTemperature.html
tidy -i -asxml ./ElementTipHelp/fr/nucleus.html -m ./ElementTipHelp/fr/nucleus.html
tidy -i -asxml ./ElementTipHelp/fr/incompatibilities.html -m ./ElementTipHelp/fr/incompatibilities.html
tidy -i -asxml ./ElementTipHelp/fr/atomicMass.html -m ./ElementTipHelp/fr/atomicMass.html
tidy -i -asxml ./ElementTipHelp/fr/vaporPressure.html -m ./ElementTipHelp/fr/vaporPressure.html
tidy -i -asxml ./ElementTipHelp/fr/hardnessScaleVickers.html -m ./ElementTipHelp/fr/hardnessScaleVickers.html
tidy -i -asxml ./ElementTipHelp/fr/electronConfiguration.html -m ./ElementTipHelp/fr/electronConfiguration.html
tidy -i -asxml ./ElementTipHelp/fr/cas.html -m ./ElementTipHelp/fr/cas.html
tidy -i -asxml ./ElementTipHelp/fr/nobleGas.html -m ./ElementTipHelp/fr/nobleGas.html
tidy -i -asxml ./ElementTipHelp/fr/descr.html -m ./ElementTipHelp/fr/descr.html
tidy -i -asxml ./ElementTipHelp/fr/period.html -m ./ElementTipHelp/fr/period.html
tidy -i -asxml ./ElementTipHelp/fr/metal.html -m ./ElementTipHelp/fr/metal.html
tidy -i -asxml ./ElementTipHelp/fr/boilingPoint.html -m ./ElementTipHelp/fr/boilingPoint.html
tidy -i -asxml ./ElementTipHelp/fr/lanthanide.html -m ./ElementTipHelp/fr/lanthanide.html
tidy -i -asxml ./ElementTipHelp/fr/proton.html -m ./ElementTipHelp/fr/proton.html
tidy -i -asxml ./ElementTipHelp/fr/lineSpectra.html -m ./ElementTipHelp/fr/lineSpectra.html
tidy -i -asxml ./ElementTipHelp/fr/iopac.html -m ./ElementTipHelp/fr/iopac.html
tidy -i -asxml ./ElementTipHelp/fr/actinide.html -m ./ElementTipHelp/fr/actinide.html
tidy -i -asxml ./ElementTipHelp/es/ionizationPotentials.html -m ./ElementTipHelp/es/ionizationPotentials.html
tidy -i -asxml ./ElementTipHelp/es/atom.html -m ./ElementTipHelp/es/atom.html
tidy -i -asxml ./ElementTipHelp/es/photon.html -m ./ElementTipHelp/es/photon.html
tidy -i -asxml ./ElementTipHelp/es/nonMetal.html -m ./ElementTipHelp/es/nonMetal.html
tidy -i -asxml ./ElementTipHelp/es/oxidationStates.html -m ./ElementTipHelp/es/oxidationStates.html
tidy -i -asxml ./ElementTipHelp/es/magneticSusceptibility.html -m ./ElementTipHelp/es/magneticSusceptibility.html
tidy -i -asxml ./ElementTipHelp/es/alkaliEarthMetal.html -m ./ElementTipHelp/es/alkaliEarthMetal.html
tidy -i -asxml ./ElementTipHelp/es/barn.html -m ./ElementTipHelp/es/barn.html
tidy -i -asxml ./ElementTipHelp/es/enthalpyOfVaporization.html -m ./ElementTipHelp/es/enthalpyOfVaporization.html
tidy -i -asxml ./ElementTipHelp/es/element.html -m ./ElementTipHelp/es/element.html
tidy -i -asxml ./ElementTipHelp/es/electroChemicalEquivalent.html -m ./ElementTipHelp/es/electroChemicalEquivalent.html
tidy -i -asxml ./ElementTipHelp/es/valenceElectronPotential.html -m ./ElementTipHelp/es/valenceElectronPotential.html
tidy -i -asxml ./ElementTipHelp/es/alkaliMetal.html -m ./ElementTipHelp/es/alkaliMetal.html
tidy -i -asxml ./ElementTipHelp/es/covalentRadius.html -m ./ElementTipHelp/es/covalentRadius.html
tidy -i -asxml ./ElementTipHelp/es/density.html -m ./ElementTipHelp/es/density.html
tidy -i -asxml ./ElementTipHelp/es/metalloid.html -m ./ElementTipHelp/es/metalloid.html
tidy -i -asxml ./ElementTipHelp/es/index.html -m ./ElementTipHelp/es/index.html
tidy -i -asxml ./ElementTipHelp/es/fillingOrbital.html -m ./ElementTipHelp/es/fillingOrbital.html
tidy -i -asxml ./ElementTipHelp/es/hardnessScales.html -m ./ElementTipHelp/es/hardnessScales.html
tidy -i -asxml ./ElementTipHelp/es/energyLevel.html -m ./ElementTipHelp/es/energyLevel.html
tidy -i -asxml ./ElementTipHelp/es/radiation.html -m ./ElementTipHelp/es/radiation.html
tidy -i -asxml ./ElementTipHelp/es/relativeGasDensity.html -m ./ElementTipHelp/es/relativeGasDensity.html
tidy -i -asxml ./ElementTipHelp/es/conduction.html -m ./ElementTipHelp/es/conduction.html
tidy -i -asxml ./ElementTipHelp/es/group.html -m ./ElementTipHelp/es/group.html
tidy -i -asxml ./ElementTipHelp/es/angstrom.html -m ./ElementTipHelp/es/angstrom.html
tidy -i -asxml ./ElementTipHelp/es/quantumNumber.html -m ./ElementTipHelp/es/quantumNumber.html
tidy -i -asxml ./ElementTipHelp/es/transitionMetal.html -m ./ElementTipHelp/es/transitionMetal.html
tidy -i -asxml ./ElementTipHelp/es/coefficientOfLinealThermalExpansion.html -m ./ElementTipHelp/es/coefficientOfLinealThermalExpansion.html
tidy -i -asxml ./ElementTipHelp/es/series.html -m ./ElementTipHelp/es/series.html
tidy -i -asxml ./ElementTipHelp/es/atomicVolume.html -m ./ElementTipHelp/es/atomicVolume.html
tidy -i -asxml ./ElementTipHelp/es/casRegistryNumber.html -m ./ElementTipHelp/es/casRegistryNumber.html
tidy -i -asxml ./ElementTipHelp/es/conductivityElectrical.html -m ./ElementTipHelp/es/conductivityElectrical.html
tidy -i -asxml ./ElementTipHelp/es/quantum.html -m ./ElementTipHelp/es/quantum.html
tidy -i -asxml ./ElementTipHelp/es/transactinide.html -m ./ElementTipHelp/es/transactinide.html
tidy -i -asxml ./ElementTipHelp/es/elasticModulusBulk.html -m ./ElementTipHelp/es/elasticModulusBulk.html
tidy -i -asxml ./ElementTipHelp/es/electronWorkFunction.html -m ./ElementTipHelp/es/electronWorkFunction.html
tidy -i -asxml ./ElementTipHelp/es/elasticModulus.html -m ./ElementTipHelp/es/elasticModulus.html
tidy -i -asxml ./ElementTipHelp/es/periodicTable.html -m ./ElementTipHelp/es/periodicTable.html
tidy -i -asxml ./ElementTipHelp/es/enthalpies.html -m ./ElementTipHelp/es/enthalpies.html
tidy -i -asxml ./ElementTipHelp/es/atomicNumber.html -m ./ElementTipHelp/es/atomicNumber.html
tidy -i -asxml ./ElementTipHelp/es/standardCondition.html -m ./ElementTipHelp/es/standardCondition.html
tidy -i -asxml ./ElementTipHelp/es/neutron.html -m ./ElementTipHelp/es/neutron.html
tidy -i -asxml ./ElementTipHelp/es/valence.html -m ./ElementTipHelp/es/valence.html
tidy -i -asxml ./ElementTipHelp/es/elasticModulusRigidity.html -m ./ElementTipHelp/es/elasticModulusRigidity.html
tidy -i -asxml ./ElementTipHelp/es/specificHeat.html -m ./ElementTipHelp/es/specificHeat.html
tidy -i -asxml ./ElementTipHelp/es/orbitalTheory.html -m ./ElementTipHelp/es/orbitalTheory.html
tidy -i -asxml ./ElementTipHelp/es/molarVolume.html -m ./ElementTipHelp/es/molarVolume.html
tidy -i -asxml ./ElementTipHelp/es/meltingPoint.html -m ./ElementTipHelp/es/meltingPoint.html
tidy -i -asxml ./ElementTipHelp/es/electron.html -m ./ElementTipHelp/es/electron.html
tidy -i -asxml ./ElementTipHelp/es/heatOfVaporization.html -m ./ElementTipHelp/es/heatOfVaporization.html
tidy -i -asxml ./ElementTipHelp/es/hardnessScaleMohs.html -m ./ElementTipHelp/es/hardnessScaleMohs.html
tidy -i -asxml ./ElementTipHelp/es/halogen.html -m ./ElementTipHelp/es/halogen.html
tidy -i -asxml ./ElementTipHelp/es/opticalReflectivity.html -m ./ElementTipHelp/es/opticalReflectivity.html
tidy -i -asxml ./ElementTipHelp/es/crystalStructure.html -m ./ElementTipHelp/es/crystalStructure.html
tidy -i -asxml ./ElementTipHelp/es/enthalpyOfAtomization.html -m ./ElementTipHelp/es/enthalpyOfAtomization.html
tidy -i -asxml ./ElementTipHelp/es/orbital.html -m ./ElementTipHelp/es/orbital.html
tidy -i -asxml ./ElementTipHelp/es/qualitativeSolubility.html -m ./ElementTipHelp/es/qualitativeSolubility.html
tidy -i -asxml ./ElementTipHelp/es/valenceElectrons.html -m ./ElementTipHelp/es/valenceElectrons.html
tidy -i -asxml ./ElementTipHelp/es/nanometer.html -m ./ElementTipHelp/es/nanometer.html
tidy -i -asxml ./ElementTipHelp/es/nuclide.html -m ./ElementTipHelp/es/nuclide.html
tidy -i -asxml ./ElementTipHelp/es/heatOfFusion.html -m ./ElementTipHelp/es/heatOfFusion.html
tidy -i -asxml ./ElementTipHelp/es/molarHeatCapacity.html -m ./ElementTipHelp/es/molarHeatCapacity.html
tidy -i -asxml ./ElementTipHelp/es/enthalpyOfFusion.html -m ./ElementTipHelp/es/enthalpyOfFusion.html
tidy -i -asxml ./ElementTipHelp/es/flammabilityClass.html -m ./ElementTipHelp/es/flammabilityClass.html
tidy -i -asxml ./ElementTipHelp/es/ionicRadius.html -m ./ElementTipHelp/es/ionicRadius.html
tidy -i -asxml ./ElementTipHelp/es/electroNegativity.html -m ./ElementTipHelp/es/electroNegativity.html
tidy -i -asxml ./ElementTipHelp/es/elasticModulusYoungs.html -m ./ElementTipHelp/es/elasticModulusYoungs.html
tidy -i -asxml ./ElementTipHelp/es/shellModel.html -m ./ElementTipHelp/es/shellModel.html
tidy -i -asxml ./ElementTipHelp/es/crossSection.html -m ./ElementTipHelp/es/crossSection.html
tidy -i -asxml ./ElementTipHelp/es/conductivityThermal.html -m ./ElementTipHelp/es/conductivityThermal.html
tidy -i -asxml ./ElementTipHelp/es/atomicRadius.html -m ./ElementTipHelp/es/atomicRadius.html
tidy -i -asxml ./ElementTipHelp/es/electroConductivity.html -m ./ElementTipHelp/es/electroConductivity.html
tidy -i -asxml ./ElementTipHelp/es/hardnessScaleBrinell.html -m ./ElementTipHelp/es/hardnessScaleBrinell.html
tidy -i -asxml ./ElementTipHelp/es/opticalRefractiveIndex.html -m ./ElementTipHelp/es/opticalRefractiveIndex.html
tidy -i -asxml ./ElementTipHelp/es/criticalTemperature.html -m ./ElementTipHelp/es/criticalTemperature.html
tidy -i -asxml ./ElementTipHelp/es/nucleus.html -m ./ElementTipHelp/es/nucleus.html
tidy -i -asxml ./ElementTipHelp/es/incompatibilities.html -m ./ElementTipHelp/es/incompatibilities.html
tidy -i -asxml ./ElementTipHelp/es/atomicMass.html -m ./ElementTipHelp/es/atomicMass.html
tidy -i -asxml ./ElementTipHelp/es/vaporPressure.html -m ./ElementTipHelp/es/vaporPressure.html
tidy -i -asxml ./ElementTipHelp/es/hardnessScaleVickers.html -m ./ElementTipHelp/es/hardnessScaleVickers.html
tidy -i -asxml ./ElementTipHelp/es/electronConfiguration.html -m ./ElementTipHelp/es/electronConfiguration.html
tidy -i -asxml ./ElementTipHelp/es/cas.html -m ./ElementTipHelp/es/cas.html
tidy -i -asxml ./ElementTipHelp/es/nobleGas.html -m ./ElementTipHelp/es/nobleGas.html
tidy -i -asxml ./ElementTipHelp/es/descr.html -m ./ElementTipHelp/es/descr.html
tidy -i -asxml ./ElementTipHelp/es/period.html -m ./ElementTipHelp/es/period.html
tidy -i -asxml ./ElementTipHelp/es/metal.html -m ./ElementTipHelp/es/metal.html
tidy -i -asxml ./ElementTipHelp/es/boilingPoint.html -m ./ElementTipHelp/es/boilingPoint.html
tidy -i -asxml ./ElementTipHelp/es/lanthanide.html -m ./ElementTipHelp/es/lanthanide.html
tidy -i -asxml ./ElementTipHelp/es/proton.html -m ./ElementTipHelp/es/proton.html
tidy -i -asxml ./ElementTipHelp/es/lineSpectra.html -m ./ElementTipHelp/es/lineSpectra.html
tidy -i -asxml ./ElementTipHelp/es/iopac.html -m ./ElementTipHelp/es/iopac.html
tidy -i -asxml ./ElementTipHelp/es/actinide.html -m ./ElementTipHelp/es/actinide.html
tidy -i -asxml ./ElementTipHelp/en/ionizationPotentials.html -m ./ElementTipHelp/en/ionizationPotentials.html
tidy -i -asxml ./ElementTipHelp/en/atom.html -m ./ElementTipHelp/en/atom.html
tidy -i -asxml ./ElementTipHelp/en/photon.html -m ./ElementTipHelp/en/photon.html
tidy -i -asxml ./ElementTipHelp/en/nonMetal.html -m ./ElementTipHelp/en/nonMetal.html
tidy -i -asxml ./ElementTipHelp/en/oxidationStates.html -m ./ElementTipHelp/en/oxidationStates.html
tidy -i -asxml ./ElementTipHelp/en/magneticSusceptibility.html -m ./ElementTipHelp/en/magneticSusceptibility.html
tidy -i -asxml ./ElementTipHelp/en/alkaliEarthMetal.html -m ./ElementTipHelp/en/alkaliEarthMetal.html
tidy -i -asxml ./ElementTipHelp/en/barn.html -m ./ElementTipHelp/en/barn.html
tidy -i -asxml ./ElementTipHelp/en/enthalpyOfVaporization.html -m ./ElementTipHelp/en/enthalpyOfVaporization.html
tidy -i -asxml ./ElementTipHelp/en/element.html -m ./ElementTipHelp/en/element.html
tidy -i -asxml ./ElementTipHelp/en/electroChemicalEquivalent.html -m ./ElementTipHelp/en/electroChemicalEquivalent.html
tidy -i -asxml ./ElementTipHelp/en/valenceElectronPotential.html -m ./ElementTipHelp/en/valenceElectronPotential.html
tidy -i -asxml ./ElementTipHelp/en/alkaliMetal.html -m ./ElementTipHelp/en/alkaliMetal.html
tidy -i -asxml ./ElementTipHelp/en/covalentRadius.html -m ./ElementTipHelp/en/covalentRadius.html
tidy -i -asxml ./ElementTipHelp/en/density.html -m ./ElementTipHelp/en/density.html
tidy -i -asxml ./ElementTipHelp/en/metalloid.html -m ./ElementTipHelp/en/metalloid.html
tidy -i -asxml ./ElementTipHelp/en/index.html -m ./ElementTipHelp/en/index.html
tidy -i -asxml ./ElementTipHelp/en/fillingOrbital.html -m ./ElementTipHelp/en/fillingOrbital.html
tidy -i -asxml ./ElementTipHelp/en/hardnessScales.html -m ./ElementTipHelp/en/hardnessScales.html
tidy -i -asxml ./ElementTipHelp/en/energyLevel.html -m ./ElementTipHelp/en/energyLevel.html
tidy -i -asxml ./ElementTipHelp/en/radiation.html -m ./ElementTipHelp/en/radiation.html
tidy -i -asxml ./ElementTipHelp/en/relativeGasDensity.html -m ./ElementTipHelp/en/relativeGasDensity.html
tidy -i -asxml ./ElementTipHelp/en/conduction.html -m ./ElementTipHelp/en/conduction.html
tidy -i -asxml ./ElementTipHelp/en/group.html -m ./ElementTipHelp/en/group.html
tidy -i -asxml ./ElementTipHelp/en/angstrom.html -m ./ElementTipHelp/en/angstrom.html
tidy -i -asxml ./ElementTipHelp/en/quantumNumber.html -m ./ElementTipHelp/en/quantumNumber.html
tidy -i -asxml ./ElementTipHelp/en/transitionMetal.html -m ./ElementTipHelp/en/transitionMetal.html
tidy -i -asxml ./ElementTipHelp/en/coefficientOfLinealThermalExpansion.html -m ./ElementTipHelp/en/coefficientOfLinealThermalExpansion.html
tidy -i -asxml ./ElementTipHelp/en/series.html -m ./ElementTipHelp/en/series.html
tidy -i -asxml ./ElementTipHelp/en/atomicVolume.html -m ./ElementTipHelp/en/atomicVolume.html
tidy -i -asxml ./ElementTipHelp/en/casRegistryNumber.html -m ./ElementTipHelp/en/casRegistryNumber.html
tidy -i -asxml ./ElementTipHelp/en/conductivityElectrical.html -m ./ElementTipHelp/en/conductivityElectrical.html
tidy -i -asxml ./ElementTipHelp/en/quantum.html -m ./ElementTipHelp/en/quantum.html
tidy -i -asxml ./ElementTipHelp/en/transactinide.html -m ./ElementTipHelp/en/transactinide.html
tidy -i -asxml ./ElementTipHelp/en/elasticModulusBulk.html -m ./ElementTipHelp/en/elasticModulusBulk.html
tidy -i -asxml ./ElementTipHelp/en/electronWorkFunction.html -m ./ElementTipHelp/en/electronWorkFunction.html
tidy -i -asxml ./ElementTipHelp/en/elasticModulus.html -m ./ElementTipHelp/en/elasticModulus.html
tidy -i -asxml ./ElementTipHelp/en/periodicTable.html -m ./ElementTipHelp/en/periodicTable.html
tidy -i -asxml ./ElementTipHelp/en/enthalpies.html -m ./ElementTipHelp/en/enthalpies.html
tidy -i -asxml ./ElementTipHelp/en/atomicNumber.html -m ./ElementTipHelp/en/atomicNumber.html
tidy -i -asxml ./ElementTipHelp/en/standardCondition.html -m ./ElementTipHelp/en/standardCondition.html
tidy -i -asxml ./ElementTipHelp/en/neutron.html -m ./ElementTipHelp/en/neutron.html
tidy -i -asxml ./ElementTipHelp/en/valence.html -m ./ElementTipHelp/en/valence.html
tidy -i -asxml ./ElementTipHelp/en/elasticModulusRigidity.html -m ./ElementTipHelp/en/elasticModulusRigidity.html
tidy -i -asxml ./ElementTipHelp/en/specificHeat.html -m ./ElementTipHelp/en/specificHeat.html
tidy -i -asxml ./ElementTipHelp/en/orbitalTheory.html -m ./ElementTipHelp/en/orbitalTheory.html
tidy -i -asxml ./ElementTipHelp/en/molarVolume.html -m ./ElementTipHelp/en/molarVolume.html
tidy -i -asxml ./ElementTipHelp/en/meltingPoint.html -m ./ElementTipHelp/en/meltingPoint.html
tidy -i -asxml ./ElementTipHelp/en/electron.html -m ./ElementTipHelp/en/electron.html
tidy -i -asxml ./ElementTipHelp/en/heatOfVaporization.html -m ./ElementTipHelp/en/heatOfVaporization.html
tidy -i -asxml ./ElementTipHelp/en/hardnessScaleMohs.html -m ./ElementTipHelp/en/hardnessScaleMohs.html
tidy -i -asxml ./ElementTipHelp/en/halogen.html -m ./ElementTipHelp/en/halogen.html
tidy -i -asxml ./ElementTipHelp/en/opticalReflectivity.html -m ./ElementTipHelp/en/opticalReflectivity.html
tidy -i -asxml ./ElementTipHelp/en/crystalStructure.html -m ./ElementTipHelp/en/crystalStructure.html
tidy -i -asxml ./ElementTipHelp/en/enthalpyOfAtomization.html -m ./ElementTipHelp/en/enthalpyOfAtomization.html
tidy -i -asxml ./ElementTipHelp/en/orbital.html -m ./ElementTipHelp/en/orbital.html
tidy -i -asxml ./ElementTipHelp/en/qualitativeSolubility.html -m ./ElementTipHelp/en/qualitativeSolubility.html
tidy -i -asxml ./ElementTipHelp/en/valenceElectrons.html -m ./ElementTipHelp/en/valenceElectrons.html
tidy -i -asxml ./ElementTipHelp/en/nanometer.html -m ./ElementTipHelp/en/nanometer.html
tidy -i -asxml ./ElementTipHelp/en/nuclide.html -m ./ElementTipHelp/en/nuclide.html
tidy -i -asxml ./ElementTipHelp/en/heatOfFusion.html -m ./ElementTipHelp/en/heatOfFusion.html
tidy -i -asxml ./ElementTipHelp/en/molarHeatCapacity.html -m ./ElementTipHelp/en/molarHeatCapacity.html
tidy -i -asxml ./ElementTipHelp/en/enthalpyOfFusion.html -m ./ElementTipHelp/en/enthalpyOfFusion.html
tidy -i -asxml ./ElementTipHelp/en/flammabilityClass.html -m ./ElementTipHelp/en/flammabilityClass.html
tidy -i -asxml ./ElementTipHelp/en/ionicRadius.html -m ./ElementTipHelp/en/ionicRadius.html
tidy -i -asxml ./ElementTipHelp/en/electroNegativity.html -m ./ElementTipHelp/en/electroNegativity.html
tidy -i -asxml ./ElementTipHelp/en/elasticModulusYoungs.html -m ./ElementTipHelp/en/elasticModulusYoungs.html
tidy -i -asxml ./ElementTipHelp/en/shellModel.html -m ./ElementTipHelp/en/shellModel.html
tidy -i -asxml ./ElementTipHelp/en/crossSection.html -m ./ElementTipHelp/en/crossSection.html
tidy -i -asxml ./ElementTipHelp/en/conductivityThermal.html -m ./ElementTipHelp/en/conductivityThermal.html
tidy -i -asxml ./ElementTipHelp/en/atomicRadius.html -m ./ElementTipHelp/en/atomicRadius.html
tidy -i -asxml ./ElementTipHelp/en/electroConductivity.html -m ./ElementTipHelp/en/electroConductivity.html
tidy -i -asxml ./ElementTipHelp/en/hardnessScaleBrinell.html -m ./ElementTipHelp/en/hardnessScaleBrinell.html
tidy -i -asxml ./ElementTipHelp/en/opticalRefractiveIndex.html -m ./ElementTipHelp/en/opticalRefractiveIndex.html
tidy -i -asxml ./ElementTipHelp/en/criticalTemperature.html -m ./ElementTipHelp/en/criticalTemperature.html
tidy -i -asxml ./ElementTipHelp/en/nucleus.html -m ./ElementTipHelp/en/nucleus.html
tidy -i -asxml ./ElementTipHelp/en/incompatibilities.html -m ./ElementTipHelp/en/incompatibilities.html
tidy -i -asxml ./ElementTipHelp/en/atomicMass.html -m ./ElementTipHelp/en/atomicMass.html
tidy -i -asxml ./ElementTipHelp/en/vaporPressure.html -m ./ElementTipHelp/en/vaporPressure.html
tidy -i -asxml ./ElementTipHelp/en/hardnessScaleVickers.html -m ./ElementTipHelp/en/hardnessScaleVickers.html
tidy -i -asxml ./ElementTipHelp/en/electronConfiguration.html -m ./ElementTipHelp/en/electronConfiguration.html
tidy -i -asxml ./ElementTipHelp/en/cas.html -m ./ElementTipHelp/en/cas.html
tidy -i -asxml ./ElementTipHelp/en/nobleGas.html -m ./ElementTipHelp/en/nobleGas.html
tidy -i -asxml ./ElementTipHelp/en/descr.html -m ./ElementTipHelp/en/descr.html
tidy -i -asxml ./ElementTipHelp/en/period.html -m ./ElementTipHelp/en/period.html
tidy -i -asxml ./ElementTipHelp/en/metal.html -m ./ElementTipHelp/en/metal.html
tidy -i -asxml ./ElementTipHelp/en/boilingPoint.html -m ./ElementTipHelp/en/boilingPoint.html
tidy -i -asxml ./ElementTipHelp/en/lanthanide.html -m ./ElementTipHelp/en/lanthanide.html
tidy -i -asxml ./ElementTipHelp/en/proton.html -m ./ElementTipHelp/en/proton.html
tidy -i -asxml ./ElementTipHelp/en/lineSpectra.html -m ./ElementTipHelp/en/lineSpectra.html
tidy -i -asxml ./ElementTipHelp/en/iopac.html -m ./ElementTipHelp/en/iopac.html
tidy -i -asxml ./ElementTipHelp/en/actinide.html -m ./ElementTipHelp/en/actinide.html
tidy -i -asxml ./ru.lproj/LoadFailure.html -m ./ru.lproj/LoadFailure.html
tidy -i -asxml ./fr.lproj/LoadFailure.html -m ./fr.lproj/LoadFailure.html
