//
//  Constants.swift
//  PrimaMateria
//
//  Created by Jerry Porter on 4/24/16.
//  Copyright © 2016 xTrensa. All rights reserved.
//

let RGB_CONSTANT : CGFloat = 255.0
let HSB_CONSTANT : CGFloat = 359.0

// MARK: Element Attributes

let ELEMENT_ABUNDANCE_CRUST : String = "abundanceCrust"
let ELEMENT_ABUNDANCE_SEA : String = "abundanceSea"
let ELEMENT_AIR_WAVELENGTH : String = "airWavelength"
let ELEMENT_ATOMIC_MASS : String = "atomicMass"
let ELEMENT_ATOMIC_MASS_AGGREGATE : String = "atomicMassAggregate"
let ELEMENT_ATOMIC_MASS_FOOTNOTE : String = "atomicMassFootnote"
let ELEMENT_ATOMIC_MASS_KNOWN_ACCURATELY : String = "atomicMassKnownAccurately"
let ELEMENT_ATOMIC_MASS_UNCERTAINTY : String = "atomicMassUncertainty"
let ELEMENT_ATOMIC_NUMBER : String = "atomicNumber"
let ELEMENT_ATOMIC_RADIUS : String = "atomicRadius"
let ELEMENT_ATOMIC_VOLUME : String = "atomicVolume"
let ELEMENT_BOILING_POINT : String = "boilingPoint"
let ELEMENT_BOILING_POINT_FOOTNOTE : String = "boilingPointFootnote"
let ELEMENT_CAS_REGISTRY_NUMBER : String = "casRegistryNumber"
let ELEMENT_COEFFICIENT_OF_LINEAL_THERMAL_EXPANSION : String = "coefficientOfLinealThermalExpansion"
let ELEMENT_CONDUCTIVITY_ELECTRICAL : String = "conductivityElectrical"
let ELEMENT_CONDUCTIVITY_THERMAL : String = "conductivityThermal"
let ELEMENT_COVALENT_RADIUS : String = "covalentRadius"
let ELEMENT_CRITICAL_TEMPERATURE : String = "criticalTemperature"
let ELEMENT_CROSS_SECTION : String = "crossSection"
let ELEMENT_CRYSTAL_STRUCTURE : String = "crystalStructure"
let ELEMENT_DENSITY : String = "density"
let ELEMENT_DESCR : String = "descr"
let ELEMENT_DISCOVERER : String = "discoverer"
let ELEMENT_DISCOVERY_LOCATION : String = "discoveryLocation"
let ELEMENT_DISCOVERY_YEAR : String = "discoveryYear"
let ELEMENT_ELASTIC_MODULUS_BULK : String = "elasticModulusBulk"
let ELEMENT_ELASTIC_MODULUS_RIGIDITY : String = "elasticModulusRigidity"
let ELEMENT_ELASTIC_MODULUS_YOUNGS : String = "elasticModulusYoungs"
let ELEMENT_ELECTRONS_RER_ENERGY_LEVEL : String = "electronsPerEnergyLevel"
let ELEMENT_ELECTRON_CONFIGURATION : String = "electronConfiguration"
let ELEMENT_ELECTRON_WORK_FUNCTION : String = "electronWorkFunction"
let ELEMENT_ELECTRO_CHEMICAL_EQUIVALENT : String = "electroChemicalEquivalent"
let ELEMENT_ELECTRO_NEGATIVITY : String = "electroNegativity"
let ELEMENT_ENTHALPY_OF_ATOMIZATION : String = "enthalpyOfAtomization"
let ELEMENT_ENTHALPY_OF_FUSION : String = "enthalpyOfFusion"
let ELEMENT_ENTHALPY_OF_VAPORIZATION : String = "enthalpyOfVaporization"
let ELEMENT_FILLING_ORBITAL : String = "fillingOrbital"
let ELEMENT_FLAMMABILITY_CLASS : String = "flammabilityClass"
let ELEMENT_GROUP : String = "group"
let ELEMENT_HARDNESS_SCALE_BRINELL : String = "hardnessScaleBrinell"
let ELEMENT_HARDNESS_SCALE_BRINELL_SCALED : String = "hardnessScaleBrinellScaled"
let ELEMENT_HARDNESS_SCALE_MOHS : String = "hardnessScaleMohs"
let ELEMENT_HARDNESS_SCALE_VICKERS : String = "hardnessScaleVickers"
let ELEMENT_HARDNESS_SCALE_VICKERS_SCALED : String = "hardnessScaleVickersScaled"
let ELEMENT_HEAT_OF_FUSION : String = "heatOfFusion"
let ELEMENT_HEAT_OF_VAPORIZATION : String = "heatOfVaporization"
let ELEMENT_INCOMPATIBILITIES : String = "incompatibilities"
let ELEMENT_INTENSITY : String = "intensity"
let ELEMENT_IONIC_RADIUS : String = "ionicRadius"
let ELEMENT_IONIZATION_POTENTIAL_FIRST : String = "ionizationPotentialFirst"
let ELEMENT_IONIZATION_POTENTIAL_SECOND : String = "ionizationPotentialSecond"
let ELEMENT_IONIZATION_POTENTIAL_THIRD : String = "ionizationPotentialThird"
let ELEMENT_KSHELL_ELECTRONS : String = "kShellElectrons"
let ELEMENT_LINE_SPECTRA : String = "lineSpectra"
let ELEMENT_LSHELL_ELECTRONS : String = "lShellElectrons"
let ELEMENT_MAGNETIC_SUSCEPTIBILITY : String = "magneticSusceptibility"
let ELEMENT_MELTING_POINT : String = "meltingPoint"
let ELEMENT_MELTING_POINT_FOOTNOTE : String = "meltingPointFootnote"
let ELEMENT_MOLAR_HEAT_CAPACITY : String = "molarHeatCapacity"
let ELEMENT_MOLAR_VOLUME : String = "molarVolume"
let ELEMENT_MSHELL_ELECTRONS : String = "mShellElectrons"
let ELEMENT_NAME : String = "name"
let ELEMENT_NSHELL_ELECTRONS : String = "nShellElectrons"
let ELEMENT_NUCLIDESANDISOTOPES : String = "nuclidesAndIsotopes"
let ELEMENT_NUMBER_OF_ELECTRONS : String = "numberOfElectrons"
let ELEMENT_NUMBER_OF_NEUTRONS : String = "numberOfNeutrons"
let ELEMENT_NUMBER_OF_PROTONS : String = "numberOfProtons"
let ELEMENT_OPTICAL_REFLECTIVITY : String = "opticalReflectivity"
let ELEMENT_OPTICAL_REFRACTIVE_INDEX : String = "opticalRefractiveIndex"
let ELEMENT_OSHELL_ELECTRONS : String = "oShellElectrons"
let ELEMENT_OXIDATION_STATES : String = "oxidationStates"
let ELEMENT_PERIOD : String = "period"
let ELEMENT_PSHELL_ELECTRONS : String = "pShellElectrons"
let ELEMENT_QSHELL_ELECTRONS : String = "qShellElectrons"
let ELEMENT_QUALITATIVE_SOLUBILITY : String = "qualitativeSolubility"
let ELEMENT_RELATIVE_GAS_DENSITY : String = "relativeGasDensity"
let ELEMENT_SERIES : String = "series"
let ELEMENT_SPECIFIC_HEAT_CAPACITY : String = "specificHeat"
let ELEMENT_SPECTRUM : String = "spectrum"
let ELEMENT_STANDARD_CONDITION : String = "standardCondition"
let ELEMENT_SYMBOL : String = "symbol"
let ELEMENT_VALENCE_ELECTRONS : String = "valenceElectrons"
let ELEMENT_VALENCE_ELECTRON_POTENTIAL : String = "valenceElectronPotential"
let ELEMENT_VAPOR_PRESSURE : String = "vaporPressure"

// MARK: - Notifications

let NOTIFICATION_ELEMENT_HELP_SELECTED : String = "elementHelpSelectedNotification"
let NOTIFICATION_GRAPH_SELECTED : String = "graphSelectedNotification"
let NOTIFICATION_TABLE_HEADER_SELECTED : String = "tableHeaderCellSelectedNotification"
let NOTIFICATION_COLOR_SELECTED : String = "colorNotification"
let NOTIFICATION_INSPECTOR_DISMISSED : String = "notificationInspectorDismissed"
let NOTIFICATION_SERIES_COLOR_CHANGED : String = "notificationSeriesColorChanged"

// MARK: - Series Text

let SERIES_ACTINIDE : String = "Actinide"
let SERIES_ALKALI_EARTH_METAL : String = "Alkali Earth Metal"
let SERIES_ALKALI_METAL : String = "Alkali Metal"
let SERIES_HALOGEN : String = "Halogen"
let SERIES_LANTHANIDE : String = "Lanthanide"
let SERIES_METAL : String = "Metal"
let SERIES_NOBLE_GAS : String = "Noble Gas"
let SERIES_NON_METAL : String = "Non Metal"
let SERIES_TRANSACTINIDES : String = "Transactinide"
let SERIES_TRANSITION_METAL : String = "Transition Metal"

// MARK: - Standard Condition Text

let STANDARD_CONDITION_GAS : String = "Gas"
let STANDARD_CONDITION_LIQUID : String = "Liquid"
let STANDARD_CONDITION_SOLID : String = "Solid"
let STANDARD_CONDITION_SYNTHETIC : String = "Synthetic"

// MARK: - Miscellaneous

let ELEMENT_BUBBLE_DEFAULT : String = "elementBubbleState"
let SHOW_TRANSITIONS_DEFAULT : String = "showViewTransitionsState"
let SPLASH_SCREEN_DEFAULT : String = "splashScreenState"
let STRING_EMPTY : String = ""
let STRING_UNKNOWN : String = "Unknown"
let SUPPORTING_FILES : String = "SupportingFiles"
let PERIODIC_VIEW_TITLE : String = "Periodic Table of the Elements"
let VIEW_TITLE_KEY : String = "viewTitle"
let SERIES_COLOR_KEY : String = "seriesColorKey"
let FILE_TYPE_PNG : String = "png"
let FILE_TYPE_RTF : String = "rtf"
let FILE_TYPE_HTML : String = "html"

// MARK: - Color Constants

let BRIGHTNESS_COLOR_COMPONENT : String = "brightness"
let HUE_COLOR_COMPONENT : String = "hue"
let SATURATION_COLOR_COMPONENT : String = "saturation"
let RED_COLOR_COMPONENT : String = "red"
let GREEN_COLOR_COMPONENT : String = "green"
let BLUE_COLOR_COMPONENT : String = "blue"

// MARK: - Storyboard

let SHOW_INSPECTOR_FROM_PERIODIC_TABLE : String = "showInspectorFromPeriodicTable"
let SHOW_INSPECTOR_FROM_GRAPH_VIEW : String = "showInspectorFromGraphView"
let SHOW_INSPECTOR_FROM_ELEMENT_LIST : String = "showInspectorFromElementList"
let SHOW_INSPECTOR_FROM_ELEMENT_BALLOON : String = "showInspectorFromElementBalloon"
let SHOW_WIKIPEDIA_VIEW_CONTROLLER_FROM_GENERAL_VIEW_CONTROLLER : String = "showWikipediaViewControllerFromGeneralViewController"
let SHOW_SPLASH_VIEW_CONTROLLER : String = "showSplashViewController"
let MAIN_STORY_BOARD : String = "MainStoryboard"
