tidy -i -asxml ./ru/index.html -m ./ru/index.html
tidy -i -asxml ./ru/License.html -m ./ru/License.html
tidy -i -asxml ./ru/GeneralInfo.html -m ./ru/GeneralInfo.html
tidy -i -asxml ./ru/ReleaseNotes.html -m ./ru/ReleaseNotes.html
tidy -i -asxml ./ru/References.html -m ./ru/References.html
tidy -i -asxml ./fr/index.html -m ./fr/index.html
tidy -i -asxml ./fr/License.html -m ./fr/License.html
tidy -i -asxml ./fr/GeneralInfo.html -m ./fr/GeneralInfo.html
tidy -i -asxml ./fr/ReleaseNotes.html -m ./fr/ReleaseNotes.html
tidy -i -asxml ./fr/References.html -m ./fr/References.html
tidy -i -asxml ./es/index.html -m ./es/index.html
tidy -i -asxml ./es/License.html -m ./es/License.html
tidy -i -asxml ./es/GeneralInfo.html -m ./es/GeneralInfo.html
tidy -i -asxml ./es/ReleaseNotes.html -m ./es/ReleaseNotes.html
tidy -i -asxml ./es/References.html -m ./es/References.html
tidy -i -asxml ./en/index.html -m ./en/index.html
tidy -i -asxml ./en/License.html -m ./en/License.html
tidy -i -asxml ./en/GeneralInfo.html -m ./en/GeneralInfo.html
tidy -i -asxml ./en/ReleaseNotes.html -m ./en/ReleaseNotes.html
tidy -i -asxml ./en/References.html -m ./en/References.html